### ISSUE TITLE
Alma.py is not launching up

### ISSUE THREAD

**Issue by mano2991** [sollan/alma#27]
`Operting system - Ubuntu 20.04`

Steps to do the installation. 

With anaconda already installed:

```
conda create --name alma
conda activate alma
conda install -c conda-forge python=3.8.5
conda install -c conda-forge wxPython
git clone https://github.com/sollan/alma.git
cd alma
pip install -r requirements.txt
```

Started the program with `python./alma.py`

the below error pops up
```
Traceback (most recent call last):
  File "./alma.py", line 2, in <module>
    from Panels import Start, AnalyzeStride, AnalyzeFootfall, RandomForest, PCA
  File "/home/ivlab/Downloads/alma/Panels/RandomForest.py", line 3, in <module>
    from Functions import ConfigFunctions, DataAnalysisFunctions
  File "/home/ivlab/Downloads/alma/Functions/DataAnalysisFunctions.py", line 13, in <module>
    mpl.style.use('seaborn')
  File "/home/ivlab/miniconda3/envs/alma/lib/python3.8/site-packages/matplotlib/style/core.py", line 147, in use
    for style in map(fix_style, styles):
  File "/home/ivlab/miniconda3/envs/alma/lib/python3.8/site-packages/matplotlib/style/core.py", line 143, in fix_style
    _api.warn_deprecated("3.6", message=_DEPRECATED_SEABORN_MSG)
  File "/home/ivlab/miniconda3/envs/alma/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 96, in warn_deprecated
    warn_external(warning, category=MatplotlibDeprecationWarning)
  File "/home/ivlab/miniconda3/envs/alma/lib/python3.8/site-packages/matplotlib/_api/__init__.py", line 363, in warn_external
    warnings.warn(message, category, stacklevel)
matplotlib._api.deprecation.MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
```

**Comment by sollan** [comment]
Based on the warning message, you could try downgrading `matplotlib`. See https://github.com/sollan/alma/issues/25:

> The following two packages have to lower the version.
> Matplotlib 3.6.2->3.5.3
> Seaborn 0.12.3 -> 0.11.1

**Comment by mano2991** [comment]
@sollan thanks its working alma is starting up but getting an warning message 

```
python ./alma.py               
Gtk-Message: 10:41:12.697: Failed to load module "atk-bridge"
Gtk-Message: 10:41:12.701: Failed to load module "canberra-gtk-module"
```
![image](https://user-images.githubusercontent.com/13638496/217723853-46f58766-662c-49b0-910a-d273b2094a83.png)

**Comment by sollan** [comment]
Hi! If this doesn't prevent the GUI from starting / working properly, then the warnings can be ignored. Otherwise you might want to check if the modules mentioned are installed, or as this thread suggests - https://github.com/DeepLabCut/DeepLabCut/issues/1012 - your `wxPython` version.

**Comment by VenkateshLab** [comment]
@sollan now new error pops us saying

```
 Traceback (most recent call last):
  File "/home/ivlab/Downloads/alma/Panels/AnalyzeFootfall.py", line 158, in SavePredFunc
    FootfallFunctions.make_output(pathname, self.df, self.t_pred, self.depth_pred, self.start_pred, self.end_pred, self.bodypart_list_pred, self.slip_fall_pred, self.frame_rate)
AttributeError: 'AnalyzeFootfallPanel' object has no attribute 't_pred'
Traceback (most recent call last):
  File "/home/ivlab/Downloads/alma/Panels/AnalyzeFootfall.py", line 832, in DisplayFootfall_UI_2
    self.Footfall_UI_2()
  File "/home/ivlab/Downloads/alma/Panels/AnalyzeFootfall.py", line 598, in Footfall_UI_2
    if self.n_pred is not None:
AttributeError: 'AnalyzeFootfallPanel' object has no attribute 'n_pred'
```

![Screenshot from 2023-02-18 14-11-59](https://user-images.githubusercontent.com/118877790/219850990-f3a35471-32d9-44a2-a02a-958a9de06d46.png)

**Comment by sollan** [comment]
@VenkateshLab Isn't this the same issue that you asked in #26?

Since the launching problem has been solved, I'll close this thread. If you have follow up questions regarding the `n_pred` attribute error, please open a new issue and provide the steps you took, as well as some example data, so that we can identify the problem, since it's most likely specific to your DLC data.
