### ISSUE TITLE
Error installing -r requirements.txt

### ISSUE THREAD

**Issue by josh-oloro** [sollan/alma#41]
Hi there. I am trying to install and use the ALMA Toolbox for the first time. However there is a problem when installing the requirements. Below is the error code. 

My operating system is macOS 12.5.1 and I am operating in Python 3.10 virtual environment. I have NumPy Version: 1.26.3. 

Thanks for the help and looking forward to using the ALMA Toolbox.

```
Collecting numpy<=1.19,>=1.18.2 (from -r requirements.txt (line 3))
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py", line 235, in <module>
          main()
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-install-gsf6za_8/numpy_1e9ba349238c43bc891e42abd0323d0b/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.10/bin/python3', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-build-env-w3yve2iv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-build-env-w3yve2iv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/hg/mt9c8y8x289f12jsw8tz1q_40000gn/T/pip-build-env-w3yve2iv/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 274, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.

```

**Comment by josh-oloro** [comment]
Hi, I would like to follow-up on this please. Thanks.

**Comment by sollan** [comment]
Hi, if I understand correctly, the error arises when you run `pip install`. However, the installation and library versions for Python 3.10 using Anaconda has been proven to work. Can you please check the answer here - https://github.com/sollan/alma/issues/40#issuecomment-2119370543 - and let me know if this works?

**Comment by alms93** [comment]
This project has recently been updated with a major v2 release.
This issue is quite old, and it may already be fixed or no longer relevant in the new version.

If you're still experiencing this in v2, feel free to reopen the issue or open a new one.
Thanks again for contributing!
